### ISSUE TITLE
bird-bgp Agentx

### ISSUE THREAD

**Issue by zetorzeszow** [carosio/bird-snmp-agent#2]
Hi,
I try run agent on router with installed BIRD and after few second he return this error:

```
bird-bgp AgentX starting
NET-SNMP version 5.7.2.1 AgentX subagent connected
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 314, in 'calling callback function'
  File "/usr/share/bird-snmp/adv_agentx.py", line 372, in _handler_wrapper
    AXObject.GlobalsRun('OnUpdate')
  File "/usr/share/bird-snmp/adv_agentx.py", line 609, in GlobalsRun
    self.Globals[name](self, self.AXData)
  File "./bird_bgp.py", line 78, in <lambda>
    "OnUpdate"      : lambda ax, axd: OnUpdate(ax,axd,bird.getBGPState())
  File "/usr/share/bird-snmp/birdagent.py", line 248, in getBGPState
    self.bgp_states[match.group(1).lower()]
KeyError: 'down'
```
I want to integrate bird with librenms.

**Comment by mikenowak** [comment]
Hi @zetorzeszow , we spoke earlier in the week, and you disappeared before I had a chance to share this with you.

I confirmed that I had this working with LibreNMS in my setup.

Here is a diff vs this code base:

```
diff --git a/bird_bgp.py b/bird_bgp.py
index 6de2bca..143adb5 100755
--- a/bird_bgp.py
+++ b/bird_bgp.py
@@ -43,7 +43,8 @@ def OnUpdate(ax, axd, state):
        ## register variables
        axd.RegisterVar('bgp', 0)
        axd.RegisterVar('bgpVersion', "10")
-       axd.RegisterVar('bgpLocalAs', state.get("bgpLocalAs"))
+       axd.RegisterVar('bgpLocalAs', 0)
+       axd.RegisterVar('bgpLocalAs.0', state.get("bgpLocalAs"))
 
        # reindex by bgpPeerRemoteAddr
        peers = {}
@@ -51,7 +52,7 @@ def OnUpdate(ax, axd, state):
                peers[peer.get("bgpPeerRemoteAddr")] = peer
 
        for snmpkey in BirdAgent.bgp_keys:
-               #axd.RegisterVar(snmpkey, 0)
+               axd.RegisterVar(snmpkey, 0)
                for peer in sorted(peers.keys(), BirdAgent.ipCompare):
                        oid = "%s.%s"%(snmpkey, peer)
                        if peers[peer].has_key(snmpkey):
diff --git a/birdagent.py b/birdagent.py
index ad44b92..a05a2c3 100644
--- a/birdagent.py
+++ b/birdagent.py
@@ -40,7 +40,7 @@ class BirdAgent:
        }
 
        _re_config_include = re.compile("^include\s*\"(/[^\"]*)\".*$")
-       _re_config_bgp_proto_begin = re.compile("^protocol bgp ([a-zA-Z0-9_]+) \{$")
+       _re_config_bgp_proto_begin = re.compile("^protocol bgp ([a-zA-Z0-9_]+) .* \{$")
        _re_config_local_as = re.compile("local ([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+) as ([0-9]+);")
        _re_config_bgp_holdtime = re.compile("hold time ([0-9]+);")
        _re_config_bgp_keepalive = re.compile("keepalive time ([0-9]+);")
@@ -99,8 +99,11 @@ class BirdAgent:
 
        bgp_defaults = {
                        'bgpPeerIdentifier':                    SnmpIpAddress("0.0.0.0"),
+                       'bgpPeerLocalAddr':                     SnmpIpAddress("0.0.0.0"),
                        'bgpPeerHoldTime':                      0,
+                       'bgpPeerHoldTimeConfigured':            0,
                        'bgpPeerKeepAlive':                     0,
+                       'bgpPeerKeepAliveConfigured':           0,
                        'bgpPeerState':                         1,
                        'bgpPeerInUpdates':                     SnmpCounter32(0),
                        'bgpPeerOutUpdates':                    SnmpCounter32(0),
@@ -234,6 +237,7 @@ class BirdAgent:
                        match = self._re_birdcli_bgp_begin.search(line)
                        if match:
                                bgp_proto = match.group(1)
+                               state["bgp-peers"][bgp_proto] = {}
                                timestamp = int(match.group(2))
                                if not state["bgp-peers"].has_key(bgp_proto):
                                        print("WARNING: proto \"%s\" not in config, skipping"%bgp_proto)
```

Hope this helps.

**Comment by zetorzeszow** [comment]
Hi @mikenowak ,
Thanks, but the issue is still. At first glance, it's ok:
> bird-bgp AgentX starting
NET-SNMP version 5.7.2.1 AgentX subagent connected

when i try snmpwalk, bird_bgp.py put this error:

> Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 314, in 'calling callback function'
  File "/usr/share/bird-snmp/adv_agentx.py", line 372, in _handler_wrapper
    AXObject.GlobalsRun('OnUpdate')
  File "/usr/share/bird-snmp/adv_agentx.py", line 609, in GlobalsRun
    self.Globals[name](self, self.AXData)
  File "./bird_bgp.py", line 81, in <lambda>
    "OnUpdate"      : lambda ax, axd: OnUpdate(ax,axd,bird.getBGPState())
  File "/usr/share/bird-snmp/birdagent.py", line 253, in getBGPState
    self.bgp_states[match.group(1).lower()]
KeyError: 'down'

**Comment by mikenowak** [comment]
Can you try https://github.com/mikenowak/bird-snmp-agent - I recently done some code cleanup and fixed a few bugs - so that might be addressed there, oh and jump on irc if you need help troubleshooting further.

**Comment by mikenowak** [comment]
I did not immediately catch this, but I am believe one of your protocols is in state "down", which isn't one of the valid states defined by BGP4-MIB.

The list of valid states is defined in script as follows:

```
    bgp_states = {
        "idle": 1,
        "connect": 2,
        "active": 3,
        "opensent": 4,
        "openconfirm": 5,
        "established": 6,
    }
```

In order to let us assist you further, can you provide (redacted if needed) output of `birdc show protocols all` as well as a relevant bit of the configuration for the down'ed protocol?

**Comment by zetorzeszow** [comment]
I have few protocols in state "established" and few is "down". Now I put your version and status look like: 

> root@BGP-1:/usr/local/bird-snmp-agent# systemctl status bird-snmp.service
● bird-snmp.service - BIRD SNMP Agent
   Loaded: loaded (/etc/systemd/system/bird-snmp.service; disabled)
   Active: failed (Result: exit-code) since nie 2018-03-25 17:09:42 CEST; 12s ago
  Process: 4266 ExecStop=/bin/kill -s TERM $MAINPID (code=exited, status=0/SUCCESS)
  Process: 4262 ExecStart=/usr/bin/env python3 /usr/local/bird-snmp-agent/bird_bgp.py (code=exited, status=1/FAILURE)
 Main PID: 4262 (code=exited, status=1/FAILURE)
mar 25 17:09:41 BGP-1 systemd[1]: Started BIRD SNMP Agent.
mar 25 17:09:41 BGP-1 env[4262]: Traceback (most recent call last):
mar 25 17:09:41 BGP-1 env[4262]: File "/usr/local/bird-snmp-agent/bird_bgp.py", line 22, in <module>
mar 25 17:09:41 BGP-1 env[4262]: from birdagent import BirdAgent
mar 25 17:09:41 BGP-1 env[4262]: File "/usr/local/bird-snmp-agent/birdagent.py", line 21, in <module>
mar 25 17:09:41 BGP-1 env[4262]: from past.builtins import cmp
mar 25 17:09:41 BGP-1 env[4262]: ImportError: No module named 'past'
mar 25 17:09:41 BGP-1 systemd[1]: bird-snmp.service: main process exited, code=exited, status=1/FAILURE
mar 25 17:09:42 BGP-1 systemd[1]: Unit bird-snmp.service entered failed state.

**Comment by mikenowak** [comment]
`apt install python3-future` will fix that `No module named 'past'` - thanks - I will update the documentation to reflect this.

Going back to your original problem, I never seen a protocol in a `down` state - so can you tell me what bird version are you using?

**Comment by mikenowak** [comment]
@zetorzeszow , the error seen in comment that you had removed was due to the fact that script could not read the bird.conf - I've added a error handling routine in my version to ensure the error is human readable shall this happen again.

As to these down protocols I will have a think about these.

**Comment by zetorzeszow** [comment]
@mikenowak , yes the errors are simplest to diagnose. You can put info to change permission to read for *snmp* user "/run/bird/bird.ctl". Below are current errors: 

> Mar 26 08:30:43 BGP-1 env[6122]: Traceback (most recent call last):
Mar 26 08:30:43 BGP-1 env[6122]: File "_ctypes/callbacks.c", line 277, in 'calling callback function'
Mar 26 08:30:43 BGP-1 env[6122]: File "/usr/local/bird-snmp-agent/adv_agentx.py", line 464, in _handler_wrapper
Mar 26 08:30:43 BGP-1 env[6122]: AXObject.GlobalsRun('OnUpdate')
Mar 26 08:30:43 BGP-1 env[6122]: File "/usr/local/bird-snmp-agent/adv_agentx.py", line 713, in GlobalsRun
Mar 26 08:30:43 BGP-1 env[6122]: self.Globals[name](self, self.AXData)
Mar 26 08:30:43 BGP-1 env[6122]: File "/usr/local/bird-snmp-agent/bird_bgp.py", line 92, in <lambda>
Mar 26 08:30:43 BGP-1 env[6122]: "OnUpdate": lambda ax, axd: OnUpdate(ax, axd, bird.getBGPState())
Mar 26 08:30:43 BGP-1 env[6122]: File "/usr/local/bird-snmp-agent/birdagent.py", line 268, in getBGPState
Mar 26 08:30:43 BGP-1 env[6122]: match.group(1))
Mar 26 08:30:43 BGP-1 env[6122]: KeyError: 'en'

**Comment by mikenowak** [comment]
It is already in the documentation, but will make sure stands out, thanks for that.

can you show me the output of 

`birdc show protocol en all`

I think the update counters are not properly matched in the regex.

**Comment by zetorzeszow** [comment]
> en BGP      master   up     2018-01-23 05:30:02  Established   
  Description:    En
  Preference:     100
  Input filter:   in_en
  Output filter:  out_en
  Import limit:   700000
    Action:       restart
  Routes:         630014 imported, 681735 exported, 1342 preferred
  Route change stats:     received   rejected   filtered    ignored   accepted
    Import updates:       55583226          0          0    4955638   50627588
    Import withdraws:     10018853          0        ---      54492    9964361
    Export updates:       47949463    7469729          0        ---   40479734
    Export withdraws:      2452718        ---        ---        ---    6196978
  BGP state:          Established
    Neighbor address: xxx.xxx.xxx.254
    Neighbor AS:      xxxx9
    Neighbor ID:      xxx.xxx.xxx.1
    Neighbor caps:    refresh restart-aware AS4
    Session:          external AS4
    Source address:   xxx.xxx.xxx.253
    Route limit:      630014/700000
    Hold timer:       199/240
    Keepalive timer:  43/80

**Comment by zetorzeszow** [comment]
Solved in : https://github.com/mikenowak/bird-snmp-agent
